export = {
  userId: '',
  slug_url: '',
  name: '',
  portfolio: {
    bio: '',
    bio_title: '',
    hero_image: '',
    hero_title: '',
    profile_image: '',
    theme: {
      background: '#151619',
      primary: '#1976d3',
      secondary: 'yellow',
      tertiary: '#ffffff',
      background_secondary: '#1e1f23',
      font: ['Arial', 'Helvetica', 'sans-serif'],
    },
    layout: ['Skills', 'Work Experience', 'Projects', 'About me'],
    projects: [],
    contact_me: {
      phone: '',
      email: '',
      social_media: {
        github: '',
        facebook: '',
        linkedin: '',
        instagram: '',
        twitter: '',
        youtube: '',
      },
      location: '',
    },
    work_history: [],
    skills: [],
  },
};
